services:
  postgres:
    image: postgres:16-alpine
    container_name: AI-Knowledge-Assistant_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: AI-Knowledge-Assistant
      POSTGRES_PASSWORD: AI-Knowledge-Assistant_dev_password
      POSTGRES_DB: AI-Knowledge-Assistant
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
